### ISSUE TITLE
[Loggable and ZF2] The class 'Gedmo\Loggable\Entity\LogEntry' was not found in the chain configured namespaces

### ISSUE THREAD

**Issue by BrunoSpy** [doctrine-extensions/DoctrineExtensions#833]
I saw this issue elsewhere but not the answer.
I think I configured correctly Doctrine Extensions with ZF2 as **Timestampable is working fine**.
But I can't find why Loggable fails with the following message : 

```
The class 'Gedmo\Loggable\Entity\LogEntry' was not found in the chain configured namespaces Application\Entity

#0 /home/datas/Projets/epeires2/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/MappingDriverChain.php(113): Doctrine\Common\Persistence\Mapping\MappingException::classNotFoundInNamespaces('Gedmo\Loggable\...', Array)
#1 /home/datas/Projets/epeires2/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(117): Doctrine\Common\Persistence\Mapping\Driver\MappingDriverChain->loadMetadataForClass('Gedmo\Loggable\...', Object(Doctrine\ORM\Mapping\ClassMetadata))
#2 /home/datas/Projets/epeires2/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(318): Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata(Object(Doctrine\ORM\Mapping\ClassMetadata), NULL, false, Array)
#3 /home/datas/Projets/epeires2/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(211): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata('Gedmo\Loggable\...')
#4 /home/datas/Projets/epeires2/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(295): Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor('Gedmo\Loggable\...')
#5 /home/datas/Projets/epeires2/vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/LoggableListener.php(223): Doctrine\ORM\EntityManager->getClassMetadata('Gedmo\Loggable\...')
#6 /home/datas/Projets/epeires2/vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/LoggableListener.php(193): Gedmo\Loggable\LoggableListener->createLogEntry('update', Object(Application\Entity\CustomFieldValue), Object(Gedmo\Loggable\Mapping\Event\Adapter\ORM))
#7 /home/datas/Projets/epeires2/vendor/doctrine/common/lib/Doctrine/Common/EventManager.php(59): Gedmo\Loggable\LoggableListener->onFlush(Object(Doctrine\ORM\Event\OnFlushEventArgs))
#8 /home/datas/Projets/epeires2/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(3199): Doctrine\Common\EventManager->dispatchEvent('onFlush', Object(Doctrine\ORM\Event\OnFlushEventArgs))
#9 /home/datas/Projets/epeires2/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(324): Doctrine\ORM\UnitOfWork->dispatchOnFlushEvent()
#10 /home/datas/Projets/epeires2/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(389): Doctrine\ORM\UnitOfWork->commit(NULL)
#11 /home/datas/Projets/epeires2/module/Application/src/Application/Controller/EventsController.php(122): Doctrine\ORM\EntityManager->flush()
#12 /home/datas/Projets/epeires2/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(83): Application\Controller\EventsController->saveAction()
#13 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#14 /home/datas/Projets/epeires2/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#15 /home/datas/Projets/epeires2/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /home/datas/Projets/epeires2/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 /home/datas/Projets/epeires2/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#18 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#19 /home/datas/Projets/epeires2/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#20 /home/datas/Projets/epeires2/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#21 /home/datas/Projets/epeires2/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(309): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#22 /home/datas/Projets/epeires2/public/index.php(17): Zend\Mvc\Application->run()
```

The entity is very simple : 

``` php
<?php
/**
 * Epeires 2
 *
 *
 * @copyright Copyright (c) 2013 Bruno Spyckerelle
 * @license   https://www.gnu.org/licenses/agpl-3.0.html Affero Gnu Public License
 */
namespace Application\Entity;

use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;
/**
 * @ORM\Entity
 * @ORM\Table(name="customfieldvalues")
 * @Gedmo\Loggable
 */
class CustomFieldValue {
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="Event", inversedBy="custom_fields_values")
     */
    protected $event;

    /**
     * @ORM\ManyToOne(targetEntity="CustomField", inversedBy="values")
     */
    protected $customfield;

    /** 
     * @ORM\Column(type="string")
     * @Gedmo\Versioned
     */
    protected $value;

    public function setEvent($event){
        $this->event = $event;
    }

    public function setCustomField($customfield){
        $this->customfield = $customfield;
    }

    public function setValue($value){
        $this->value = $value;
    }

    public function getValue(){
        return $this->value;
    }
}
```

What am I missing ?

Info : modules' version:

```
  doctrine/annotations               v1.1.2             Docblock Annotations Parser
  doctrine/cache                     v1.1               Caching library offering an object-oriented API for many cache backends
  doctrine/collections               v1.1               Collections Abstraction library
  doctrine/common                    v2.4.1             Common Library for Doctrine projects
  doctrine/dbal                      v2.4.0             Database Abstraction Layer
  doctrine/doctrine-module           0.7.2              Zend Framework 2 Module that provides Doctrine basic functionality required for ORM and ODM modules
  doctrine/doctrine-orm-module       0.7.0              Zend Framework 2 Module that provides Doctrine ORM functionality
  doctrine/inflector                 v1.0               Common String Manipulations with regard to casing and singular/plural rules.
  doctrine/lexer                     v1.0               Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
  doctrine/orm                       v2.4.0             Object-Relational-Mapper for PHP
  gedmo/doctrine-extensions          v2.3.7             Doctrine2 behavioral extensions
  kriswallsmith/assetic              v1.1.2             Asset Management for PHP
  rwoverdijk/assetmanager            1.3.4              An assetmanager module for Zend Framework 2.
  symfony/console                    v2.3.4             Symfony Console Component
  symfony/process                    v2.3.4             Symfony Process Component
  zendframework/zend-developer-tools dev-master 9b93113 Module for developer and debug tools for working with the ZF2 MVC layer.
  zendframework/zendframework        2.2.4              Zend Framework 2

```

**Comment by nutii** [comment]
Could somebody explain what I need to do for deal with this problem?
Thanks in advance!

**Comment by smozgur** [comment]
Hi, 3.5 years and the exact same error I am dealing with. I was about to give up and find this unique and short conversation. Sluggable **works** without problems and all other parts of Doctrine with Entities **but** Loggable.

Could you please help me to understand the magic answer that looks to be solver of the problem? 
Thank you very much.

Following is my doctrine drive settings including extension listeners:

```
'doctrine' => [
        'driver' => [
            __NAMESPACE__ . '_driver' => [
                'class' => AnnotationDriver::class,
                'cache' => 'array',
                'paths' => [__DIR__ . '/../src/Entity']
            ],
            'orm_default' => [
                'drivers' => [
                    __NAMESPACE__ . '\Entity' => __NAMESPACE__ . '_driver'
                ]
            ]
        ],
        'eventmanager' => [
            'orm_default' => [
                'subscribers' => [
                    \Gedmo\Loggable\LoggableListener::class,
                    \Gedmo\Sortable\SortableListener::class,
                ]
            ]
        ],
    ]
```

**Comment by l3pp4rd** [comment]
Hi, most likely since you are trying to use loggable, you need to register mapping driver for loggable entity or it's mapped super class. So all you need to do, is add to:

``` php
'driver' => [
            __NAMESPACE__ . '_driver' => [
                'class' => AnnotationDriver::class,
                'cache' => 'array',
                'paths' => [__DIR__ . '/../src/Entity']
            ],
```
extra path, to `__DIR__./../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity` similar like in [symfony2](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/symfony2.md#mapping) configuration samples.

The issue is that you must register all metadata in your ORM mapping driver, all you need to use in your application. That is the first thing you need to understand when starting to use ORMs.

I understand, it is all magic and stuff, lots of configuration and new concepts. but you need to understand what you are using, internet is full of similar questions and ORM has a great manual, go on and read it before you use it.

**Comment by smozgur** [comment]
Thank you very much!

To provide a little help other people like myself: I changed my configuration as below by following your instructions and especially reading the right content and updated database by using command line tool - it all worked perfect!

Thank you!

```
'doctrine' => [
        'driver' => [
            __NAMESPACE__ . '_driver' => [
                'class' => AnnotationDriver::class,
                'cache' => 'array',
                'paths' => [
                    __DIR__ . '/../src/Entity',
                    __DIR__ . '/../../../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity'
                ]
            ],
            'orm_default' => [
                'drivers' => [
                    __NAMESPACE__ . '\Entity' => __NAMESPACE__ . '_driver',
                    'Gedmo\Loggable\Entity\LogEntry' => __NAMESPACE__ . '_driver',
                ]
            ]
        ],
        'eventmanager' => [
            'orm_default' => [
                'subscribers' => [
                    \Gedmo\Loggable\LoggableListener::class,
                    \Gedmo\Sortable\SortableListener::class,
                ]
            ]
        ],
    ]
```
